FROM ubuntu
WORKDIR '/app'
COPY package.json .
RUN apt-get update
RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
RUN apt-get install -y node.js npm
COPY . .

CMD ["npm", "run", "start"]
